CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS testing (
	id		UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	todo		TEXT NOT NULL,
	message		TEXT NOT NULL,
	is_active	BOOLEAN NOT NULL DEFAULT FALSE,
	created_at	TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at	TIMESTAMP NOT NULL DEFAULT NOW()

);

